CREATE TABLE CRYPTO_CANDLES_1H (
    SYMBOL VARCHAR2(20) NOT NULL,
    OPEN_TIME_MS NUMBER NOT NULL,
    OPEN_PRICE NUMBER,
    HIGH_PRICE NUMBER,
    LOW_PRICE NUMBER,
    CLOSE_PRICE NUMBER,
    VOLUME NUMBER,
    CLOSE_TIME_MS NUMBER,
    SOURCE VARCHAR2(25),
    INGEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CANDLES_1H PRIMARY KEY (SYMBOL, OPEN_TIME_MS)
) 
ORGANIZATION INDEX;

CREATE INDEX IDX_CANDLES_TIMELINE ON CRYPTO_CANDLES_1H (SYMBOL, OPEN_TIME_MS DESC);