app:
  update_interval_seconds: 2
  timeframe: "1h"
  backfill_days: 730
  ready_threshold_hours: 1

kafka:
  broker: "localhost:19092"
  topic: "crypto-raw"

binance:
  tickers:
    - "BTCUSDT"
    - "ETHUSDT"
    - "SOLUSDT"
    - "BNBUSDT"
    - "ADAUSDT"
    - "XRPUSDT"
    - "DOTUSDT"
    - "DOGEUSDT"
    - "AVAXUSDT"
    - "LINKUSDT"
